### ISSUE TITLE
Support restricting CORS Origins

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-browser-security#19]
By default, WordPress will allow REST API requests from any Origin. It does this intentionally, as CSRF tokens ([nonces](https://developer.wordpress.org/apis/security/nonces/)) are used for cross-site protection.

To help provide defense-in-depth for cross-origin protection, we should provide helpers to help restrict allowed origins, as the threat model for Altis differs from general WordPress sites.

How exactly we want to provide this facility needs to be determined. I'd suggest the following:

* A configuration option to specify explicit hosts; `ABS_REST_ALLOWED_ORIGINS` (`array`) - default is `[ '*' ]`, which is special-cased to allow all hosts
* A filter to add hosts dynamically, `altis.security.browser.rest_allowed_origins`
* A filter to control whether a specific host is allowed, `altis.security.browser.rest_allow_origin` (`bool`) (maybe instead of the former?)
* Possibly, configuration to enable/disable domains from the same multisite network?

Decided during refinement:

* Remove default behavior from WordPress core
* Add our own logic that behaves the same way as WordPress core
* Add a filter that allows third-party code to change this behavior

### Acceptance criteria

* [x] As a developer, when I return `false` from the `altis.security.browser.rest_allow_origin` filter, the CORS header should not be sent
* [x] As a developer, when I return `true` from the `altis.security.browser.rest_allow_origin` filter, the CORS header should be sent
* [x] Without anything attached to the `altis.security.browser.rest_allow_origin` filter, the CORS header should be sent
* [x] The [Security plugin documentation](https://github.com/humanmade/altis-browser-security) documents how to use this filter
* [x] The [Browser Security](https://docs.altis-dxp.com/security/browser/) documentation page include examples of both configuration and using the filter.
* [x] [Tests](https://github.com/humanmade/altis-browser-security/blob/master/tests/class-test-content-security-policies.php) are updated to include the new behavior

**Comment by rmccue** [comment]
Might be worth considering adding a filter to WP core too for this, as right now there's no real ability in core to change this behaviour at all.

**Comment by kadamwhite** [comment]
Would there be an option to restrict by IP range, or strictly origin?

**Comment by rmccue** [comment]
Only origin; this is specifically about the [Access-Control-Allow-Origin header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin), which reflects the `Origin` header passed as part of the CORS preflight request/headers.

(IP range restrictions would be more the domain of the Altis Security module rather than Browser Security.)

**Comment by kovshenin** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Vulcan-6284e0dfb386b00c83981426/issues/humanmade/altis-browser-security/19?planning-poker) with Zenhub @jerico @mikelittle @wisyhambolu

**Comment by kovshenin** [comment]
Taking this async to determine which option to go with.

**Comment by rmccue** [comment]
`ABS` I think is what we use for the others; this (standalone) plugin is `altis-browser-security`, but hierarchically it's `Altis\Security\Browser` so the hooks match that

**Comment by kovshenin** [comment]
Decided during refinement:

* Remove default behavior from WordPress core
* Add our own logic that behaves the same way as WordPress core
* Add a filter that allows third-party code to change this behavior

**Comment by jerico** [comment]
I'm picking this up, first thing I'll try to figure out is how to remove default behavior from WordPress core

**Comment by jerico** [comment]
There's a filter that sets the header that we can remove [`add_filter( 'rest_pre_serve_request', 'rest_send_cors_headers' );`](https://github.com/WordPress/WordPress/blob/d52a8492ea5dad477664d8bafc7c80cf83d1c0bc/wp-includes/rest-api.php#L223)

```
/**
 * Sends Cross-Origin Resource Sharing headers with API requests.
 *
 * @since 4.4.0
 *
 * @param mixed $value Response data.
 * @return mixed Response data.
 */
function rest_send_cors_headers( $value ) {
	$origin = get_http_origin();

	if ( $origin ) {
		// Requests from file:// and data: URLs send "Origin: null".
		if ( 'null' !== $origin ) {
			$origin = sanitize_url( $origin );
		}
		header( 'Access-Control-Allow-Origin: ' . $origin );
		header( 'Access-Control-Allow-Methods: OPTIONS, GET, POST, PUT, PATCH, DELETE' );
		header( 'Access-Control-Allow-Credentials: true' );
		header( 'Vary: Origin', false );
	} elseif ( ! headers_sent() && 'GET' === $_SERVER['REQUEST_METHOD'] && ! is_user_logged_in() ) {
		header( 'Vary: Origin', false );
	}

	return $value;
}
```

https://github.com/WordPress/WordPress/blob/d52a8492ea5dad477664d8bafc7c80cf83d1c0bc/wp-includes/rest-api.php#L723

Need to replace this that adds our own logic.

**Comment by jerico** [comment]
Pushed a draft PR: https://github.com/humanmade/altis-browser-security/pulls

Changed approach with what was written above. `get_http_origin()` have a filter to change the origin and I'm using that instead to check origin to an array of allowed origins if this setting is enabled.

**Comment by jerico** [comment]
Ryan had a feedback with the draft PR. Addressed his feedback. Also added docs for browser-security and altis-security.

Trying to wrap my head around unit tests. Figuring out how to test CORS headers with PHPUnit.

**Comment by jerico** [comment]
Putting this back in progress to address Mike's review

**Comment by jerico** [comment]
Addressed Mike's feedback. Only needs review.
