### ISSUE TITLE
Add report-only mode for CSP

### ISSUE THREAD

**Issue by rmccue** [humanmade/altis-browser-security#6]
Follow-up from #5, props @mikeselander.

We should have the ability to set CSPs in report-only mode so that new policies can be tested out.

This will require multiple things:
* Duplicate configuration to support CSP and report-only CSP side-by-side (as you typically have both)
* A backend and endpoint to collect reports
* UI (in the admin or via a CLI) to check reports

**Comment by mikeselander** [comment]
Thanks for adding this as a feature, I think it will be really valuable!

I'm a bit hesitant to handle the actual reporting ourselves within WordPress though; if a client or user of the plugin deployed a bad directive, we could quickly get flooded by tens or hundreds of thousands of reports from larger sites. Starting with just allowing the directive to be set and requiring that developers handle the reports with a service that's designed for it (such as https://report-uri.com) would probably be just as good.

**Comment by rmccue** [comment]
I was thinking more of a loopback report, where it reports into the site's database.

That said, didn't realise there were services specifically for this, so we could potentially recommend that.

**Comment by roborourke** [comment]
Fixed by #8 - mad props @kadamwhite 

Tagged release 1.1.0 with this feature.
